logs:
  - name: "master"
    level: info
    format: "%d%T%lN%T%p%T%t%T%tN%T%C%T%f%T%l%T%m%n"
    appenders: 
      - level: info
        path: null
        type: StdLogAppender
        format: null
      - level: info
        path: log.txt
        type: FileLogAppender
        format: "%d%T%lN%T%p%T%t%T%tN%T%C%T%f%T%l%T%m%n"
coroutine:
  stacksize: 131072
tcp:
  connect: 
    timeout_ms: 5000
http:
  request:
    buffer_size: 4090
    body_maxsize: 67108864
  response:
    buffer_size: 4090
    body_maxsize: 67108864
  default_html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>404 Error</title>
        <style>
            body {
                font-family: Arial, sans-serif;
                margin: 0;
                padding: 0;
                display: flex;
                justify-content: center;
                align-items: center;
                height: 100vh;
                background-color: #f0f0f0;
                text-align: center;
            }
            .container {
                background: #fff;
                padding: 50px;
                border-radius: 8px;
                box-shadow: 0 0 10px rgba(0,0,0,0.1);
            }
            h1 {
                color: #c00;
                font-size: 3em;
            }
            p {
                color: #666;
                font-size: 1.2em;
                margin: 20px 0;
            }
            a {
                display: inline-block;
                padding: 10px 20px;
                background: #007BFF;
                color: white;
                text-decoration: none;
                border-radius: 4px;
                margin-top: 20px;
            }
            a:hover {
                background: #0056b3;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>404</h1>
            <p>抱歉，您请求的页面不存在...</p>
            <a href="/">返回首页</a>
        </div>
    </body>
    </html>
tcp_server:
  recv_timeout: -1
