logs:
  - name: "master"
    level: info
    format: "%d%T%lN%T%p%T%t%T%tN%T%C%T%f%T%l%T%m%n"
    appenders: 
      - level: info
        path: null
        type: StdLogAppender
        format: null
      - level: info
        path: log.txt
        type: FileLogAppender
        format: "%d%T%lN%T%p%T%t%T%tN%T%C%T%f%T%l%T%m%n"
coroutine:
  stacksize: 131072
tcp:
  connect: 
    timeout_ms: 5000
http:
  request:
    buffer_size: 4090
    body_maxsize: 67108864
  response:
    buffer_size: 4090
    body_maxsize: 67108864
